# Generated by Django 5.0 on 2024-10-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='mysite/static/img/usersphotos/default.png', null=True, upload_to='mysite/static/img/usersphotos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(default='', max_length=50, verbose_name='Телеграм'),
        ),
    ]
