# Generated by Django 5.0 on 2024-10-26 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(default=None, max_length=50, verbose_name='Телеграм')),
                ('register_date', models.DateField(default=django.utils.timezone.localdate)),
                ('photo', models.ImageField(blank=True, default='my_site/static/img/usersphotos/default.png', null=True, upload_to='my_site/static/img/usersphotos/', verbose_name='Фото профиля')),
                ('age', models.IntegerField(default=None, verbose_name='Возраст')),
                ('organization', models.CharField(default='Самозанятый', max_length=100, verbose_name='Организация')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
