# Generated by Django 5.1.2 on 2024-11-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_profile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='User', max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
