# Generated by Django 5.0 on 2024-11-03 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_project_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(null=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='projects', to='mysite.comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(choices=[(True, 'Закрепленный'), (False, 'Обычный')], default=False, verbose_name='Закрепленный'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(choices=[(True, 'Публичный'), (False, 'Закрытый')], default=True, verbose_name='Публичность'),
        ),
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='projects', to='mysite.like'),
        ),
    ]
