# Generated by Django 5.0 on 2024-11-03 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_project_collaborators_alter_project_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='projects', to='mysite.comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закрепленный'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный'),
        ),
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='mysite.like'),
        ),
    ]
