# Generated by Django 5.0 on 2024-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_project_collaborators_alter_project_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_public',
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный'),
        ),
    ]
