# Generated by Django 5.0 on 2024-11-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_project_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание проекта'),
        ),
    ]
