# Generated by Django 5.0 on 2024-11-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_uploadedfile_alter_comment_autor_alter_like_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(to='mysite.uploadedfile'),
        ),
    ]
