# Generated by Django 5.0 on 2024-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.ImageField(upload_to='usersprojects/'),
        ),
    ]
