# Generated by Django 5.0 on 2024-11-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(related_name='likedprojects', to='mysite.project'),
        ),
    ]
