# Generated by Django 5.0 on 2024-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_comment_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='project', to='mysite.comment'),
        ),
    ]
