# Generated by Django 5.0 on 2024-11-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_alter_comment_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Комментарии'),
        ),
    ]
