# Generated by Django 5.0 on 2024-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_notification_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[(0, 'like_project'), (1, 'like_comment'), (2, 'follow'), (3, 'delete_comment')], default=0, max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
