# Generated by Django 5.0 on 2024-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='obj_id',
            field=models.IntegerField(default=0, verbose_name='id обьекта уведомления'),
        ),
    ]
