# Generated by Django 5.0 on 2024-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_notification_obj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='obj_title',
            field=models.CharField(default='', max_length=100, verbose_name='Имя обьекта уведомления'),
        ),
    ]
