# Generated by Django 5.0 on 2024-11-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_remove_notification_autor_notification_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
    ]
