# Generated by Django 5.0 on 2024-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0037_remove_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(to='mysite.notification'),
        ),
    ]
