# Generated by Django 5.0 on 2024-11-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_profile_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
    ]
