# Generated by Django 5.0 on 2024-11-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_notification_autor_profile_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='autor',
        ),
    ]
