# Generated by Django 5.0 on 2024-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0044_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
