# Generated by Django 5.0 on 2024-11-23 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0046_profile_is_check_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localdate, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
    ]
