# Generated by Django 5.0 on 2024-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0049_achievement_profile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_id',
            field=models.IntegerField(default=0, verbose_name='Основной файл'),
        ),
    ]
