# Generated by Django 5.0 on 2024-12-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0050_project_current_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_id',
        ),
    ]
